<?php

/**
 * @file
 * Adding preprocess functions here.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_preprocess_node().
 */
function drupal_up_preprocess_node(&$variables) {
  $variables['question_wrapper']['attributes'] = new Attribute([
    'id' => 'wrapper-' . $variables['node']->id(),
    'data-js-name' => 'random',
    'class' => [
      'class-pp-1',
      'class-pp-2',
    ]
  ]);

  //dump($variables);
}
